sudo: required

services:
    - docker

before_install:
    - docker pull projectatomic/dockerfile-lint
    - ./scripts/build.sh

script:
    - ./scripts/run.sh

after_success:
    - if [ "$TRAVIS_BRANCH" == "master" ]; then
      docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
      ./scripts/push.sh;
      fi
